/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/contact-us': RouteRecordInfo<'/contact-us', '/contact-us', Record<never, never>, Record<never, never>>,
    '/my-account': RouteRecordInfo<'/my-account', '/my-account', Record<never, never>, Record<never, never>>,
    '/news': RouteRecordInfo<'/news', '/news', Record<never, never>, Record<never, never>>,
    '/product/[name]': RouteRecordInfo<'/product/[name]', '/product/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/product-category/': RouteRecordInfo<'/product-category/', '/product-category', Record<never, never>, Record<never, never>>,
    '/product-category/brands': RouteRecordInfo<'/product-category/brands', '/product-category/brands', Record<never, never>, Record<never, never>>,
    '/product-category/harold': RouteRecordInfo<'/product-category/harold', '/product-category/harold', Record<never, never>, Record<never, never>>,
    '/product-category/jarressa-estate': RouteRecordInfo<'/product-category/jarressa-estate', '/product-category/jarressa-estate', Record<never, never>, Record<never, never>>,
    '/product-category/whites-road': RouteRecordInfo<'/product-category/whites-road', '/product-category/whites-road', Record<never, never>, Record<never, never>>,
    '/shop': RouteRecordInfo<'/shop', '/shop', Record<never, never>, Record<never, never>>,
  }
}
